[workspace]
resolver = "3"
members = [
    "crates/seance-app",
    "crates/seance-bench",
    "crates/seance-config",
    "crates/seance-frame",
    "crates/seance-input",
    "crates/seance-mux-client",
    "crates/seance-mux-server",
    "crates/seance-protocol",
    "crates/seance-render",
    "crates/seance-render-test",
    "crates/seance-vt",
]

[workspace.package]
version = "0.1.0"
edition = "2024"
rust-version = "1.94"
license = "MIT OR Apache-2.0"

[workspace.dependencies]
# internal
seance-config = { path = "crates/seance-config" }
seance-frame = { path = "crates/seance-frame" }
seance-input = { path = "crates/seance-input" }
seance-mux-client = { path = "crates/seance-mux-client" }
seance-mux-server = { path = "crates/seance-mux-server" }
seance-protocol = { path = "crates/seance-protocol" }
seance-render = { path = "crates/seance-render" }
seance-vt = { path = "crates/seance-vt" }

# external
arboard = "3"
bytes = "1"
bytemuck = { version = "1", features = ["derive"] }
cosmic-text = "0.19"
tracing = "0.1"
tracing-subscriber = { version = "0.3", features = ["env-filter", "fmt", "registry", "std"] }
tracing-appender = "0.2"
etagere = "0.3"
fancy-regex = "0.19"
include_dir = "0.7"
insta = { version = "1", features = ["glob", "yaml"] }
libc = "0.2"
libghostty-vt = {
    git = "https://github.com/Uzaaft/libghostty-rs",
    rev = "5ac47e9eb166add2c00c432bc65c279133629712",
    default-features = false,
    features = ["kitty-graphics", "png"]
}
notify = "8"
notify-debouncer-full = "0.7"
objc2 = "0.6"
objc2-app-kit = "0.3"
objc2-quartz-core = "0.3"
png = "0.18"
polling = "3"
pollster = "1.0"
portable-pty = "0.9"
postcard = { version = "1", default-features = false, features = ["use-std"] }
pretty_assertions = "1"
proptest = "1"
rand_core = "0.10"
rand_pcg = "0.10"
raw-window-handle = "0.6"
rustc-hash = "2"
serde = { version = "1", features = ["derive"] }
serde-big-array = "0.5"
tiny-skia = "0.12"
toml = "1.1"
unicode-width = "0.2"
wgpu = "30"
winit = "0.30"

[workspace.lints.clippy]
collapsible_if = "warn"
