[package]
name = "seance-mux"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "Local mux facade and pane materialization for seance"

[dependencies]
# internal
seance-frame.workspace = true
seance-protocol.workspace = true
seance-vt.workspace = true

# external
bytes.workspace = true
fancy-regex.workspace = true
log.workspace = true

[dev-dependencies]
# external
pretty_assertions.workspace = true

[lints]
workspace = true
