[package]
name = "seance-app"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "seance terminal multiplexer application"

[[bin]]
name = "seance"
path = "src/main.rs"

[dependencies]
# internal
seance-config.workspace = true
seance-input.workspace = true
seance-mux.workspace = true
seance-render.workspace = true

# external
arboard.workspace = true
bytes.workspace = true
tracing.workspace = true
tracing-appender.workspace = true
tracing-subscriber.workspace = true
notify.workspace = true
notify-debouncer-full.workspace = true
pollster.workspace = true
winit.workspace = true

[target.'cfg(target_os = "macos")'.dependencies]
# external
objc2.workspace = true
objc2-app-kit.workspace = true
objc2-quartz-core.workspace = true
raw-window-handle.workspace = true

[lints]
workspace = true
