[package]
name = "seance-vt"
version.workspace = true
edition.workspace = true
rust-version.workspace = true
license.workspace = true
description = "VT emulator wrapper, PTY, and selection for seance"

[dependencies]
# internal
seance-frame.workspace = true
seance-protocol.workspace = true

# external
bytes.workspace = true
libc.workspace = true
libghostty-vt.workspace = true
png.workspace = true
polling.workspace = true
portable-pty.workspace = true
tracing.workspace = true

[lints]
workspace = true
