use libghostty_vt::key;
use winit::keyboard::KeyCode;

pub fn map_keycode(code: KeyCode) -> Option<key::Key> {
    Some(match code {
        KeyCode::Backquote => key::Key::Backquote,
        KeyCode::Backslash => key::Key::Backslash,
        KeyCode::BracketLeft => key::Key::BracketLeft,
        KeyCode::BracketRight => key::Key::BracketRight,
        KeyCode::Comma => key::Key::Comma,
        KeyCode::Digit0 => key::Key::Digit0,
        KeyCode::Digit1 => key::Key::Digit1,
        KeyCode::Digit2 => key::Key::Digit2,
        KeyCode::Digit3 => key::Key::Digit3,
        KeyCode::Digit4 => key::Key::Digit4,
        KeyCode::Digit5 => key::Key::Digit5,
        KeyCode::Digit6 => key::Key::Digit6,
        KeyCode::Digit7 => key::Key::Digit7,
        KeyCode::Digit8 => key::Key::Digit8,
        KeyCode::Digit9 => key::Key::Digit9,
        KeyCode::Equal => key::Key::Equal,
        KeyCode::IntlBackslash => key::Key::IntlBackslash,
        KeyCode::IntlRo => key::Key::IntlRo,
        KeyCode::IntlYen => key::Key::IntlYen,
        KeyCode::KeyA => key::Key::A,
        KeyCode::KeyB => key::Key::B,
        KeyCode::KeyC => key::Key::C,
        KeyCode::KeyD => key::Key::D,
        KeyCode::KeyE => key::Key::E,
        KeyCode::KeyF => key::Key::F,
        KeyCode::KeyG => key::Key::G,
        KeyCode::KeyH => key::Key::H,
        KeyCode::KeyI => key::Key::I,
        KeyCode::KeyJ => key::Key::J,
        KeyCode::KeyK => key::Key::K,
        KeyCode::KeyL => key::Key::L,
        KeyCode::KeyM => key::Key::M,
        KeyCode::KeyN => key::Key::N,
        KeyCode::KeyO => key::Key::O,
        KeyCode::KeyP => key::Key::P,
        KeyCode::KeyQ => key::Key::Q,
        KeyCode::KeyR => key::Key::R,
        KeyCode::KeyS => key::Key::S,
        KeyCode::KeyT => key::Key::T,
        KeyCode::KeyU => key::Key::U,
        KeyCode::KeyV => key::Key::V,
        KeyCode::KeyW => key::Key::W,
        KeyCode::KeyX => key::Key::X,
        KeyCode::KeyY => key::Key::Y,
        KeyCode::KeyZ => key::Key::Z,
        KeyCode::Minus => key::Key::Minus,
        KeyCode::Period => key::Key::Period,
        KeyCode::Quote => key::Key::Quote,
        KeyCode::Semicolon => key::Key::Semicolon,
        KeyCode::Slash => key::Key::Slash,
        KeyCode::AltLeft => key::Key::AltLeft,
        KeyCode::AltRight => key::Key::AltRight,
        KeyCode::Backspace => key::Key::Backspace,
        KeyCode::CapsLock => key::Key::CapsLock,
        KeyCode::ContextMenu => key::Key::ContextMenu,
        KeyCode::ControlLeft => key::Key::ControlLeft,
        KeyCode::ControlRight => key::Key::ControlRight,
        KeyCode::Enter => key::Key::Enter,
        KeyCode::SuperLeft => key::Key::MetaLeft,
        KeyCode::SuperRight => key::Key::MetaRight,
        KeyCode::ShiftLeft => key::Key::ShiftLeft,
        KeyCode::ShiftRight => key::Key::ShiftRight,
        KeyCode::Space => key::Key::Space,
        KeyCode::Tab => key::Key::Tab,
        KeyCode::Convert => key::Key::Convert,
        KeyCode::KanaMode => key::Key::KanaMode,
        KeyCode::NonConvert => key::Key::NonConvert,
        KeyCode::Delete => key::Key::Delete,
        KeyCode::End => key::Key::End,
        KeyCode::Help => key::Key::Help,
        KeyCode::Home => key::Key::Home,
        KeyCode::Insert => key::Key::Insert,
        KeyCode::PageDown => key::Key::PageDown,
        KeyCode::PageUp => key::Key::PageUp,
        KeyCode::ArrowDown => key::Key::ArrowDown,
        KeyCode::ArrowLeft => key::Key::ArrowLeft,
        KeyCode::ArrowRight => key::Key::ArrowRight,
        KeyCode::ArrowUp => key::Key::ArrowUp,
        KeyCode::NumLock => key::Key::NumLock,
        KeyCode::Numpad0 => key::Key::Numpad0,
        KeyCode::Numpad1 => key::Key::Numpad1,
        KeyCode::Numpad2 => key::Key::Numpad2,
        KeyCode::Numpad3 => key::Key::Numpad3,
        KeyCode::Numpad4 => key::Key::Numpad4,
        KeyCode::Numpad5 => key::Key::Numpad5,
        KeyCode::Numpad6 => key::Key::Numpad6,
        KeyCode::Numpad7 => key::Key::Numpad7,
        KeyCode::Numpad8 => key::Key::Numpad8,
        KeyCode::Numpad9 => key::Key::Numpad9,
        KeyCode::NumpadAdd => key::Key::NumpadAdd,
        KeyCode::NumpadBackspace => key::Key::NumpadBackspace,
        KeyCode::NumpadClear => key::Key::NumpadClear,
        KeyCode::NumpadClearEntry => key::Key::NumpadClearEntry,
        KeyCode::NumpadComma => key::Key::NumpadComma,
        KeyCode::NumpadDecimal => key::Key::NumpadDecimal,
        KeyCode::NumpadDivide => key::Key::NumpadDivide,
        KeyCode::NumpadEnter => key::Key::NumpadEnter,
        KeyCode::NumpadEqual => key::Key::NumpadEqual,
        KeyCode::NumpadMemoryAdd => key::Key::NumpadMemoryAdd,
        KeyCode::NumpadMemoryClear => key::Key::NumpadMemoryClear,
        KeyCode::NumpadMemoryRecall => key::Key::NumpadMemoryRecall,
        KeyCode::NumpadMemoryStore => key::Key::NumpadMemoryStore,
        KeyCode::NumpadMemorySubtract => key::Key::NumpadMemorySubtract,
        KeyCode::NumpadMultiply => key::Key::NumpadMultiply,
        KeyCode::NumpadParenLeft => key::Key::NumpadParenLeft,
        KeyCode::NumpadParenRight => key::Key::NumpadParenRight,
        KeyCode::NumpadSubtract => key::Key::NumpadSubtract,
        KeyCode::Escape => key::Key::Escape,
        KeyCode::Fn => key::Key::Fn,
        KeyCode::FnLock => key::Key::FnLock,
        KeyCode::PrintScreen => key::Key::PrintScreen,
        KeyCode::ScrollLock => key::Key::ScrollLock,
        KeyCode::Pause => key::Key::Pause,
        KeyCode::F1 => key::Key::F1,
        KeyCode::F2 => key::Key::F2,
        KeyCode::F3 => key::Key::F3,
        KeyCode::F4 => key::Key::F4,
        KeyCode::F5 => key::Key::F5,
        KeyCode::F6 => key::Key::F6,
        KeyCode::F7 => key::Key::F7,
        KeyCode::F8 => key::Key::F8,
        KeyCode::F9 => key::Key::F9,
        KeyCode::F10 => key::Key::F10,
        KeyCode::F11 => key::Key::F11,
        KeyCode::F12 => key::Key::F12,
        KeyCode::F13 => key::Key::F13,
        KeyCode::F14 => key::Key::F14,
        KeyCode::F15 => key::Key::F15,
        KeyCode::F16 => key::Key::F16,
        KeyCode::F17 => key::Key::F17,
        KeyCode::F18 => key::Key::F18,
        KeyCode::F19 => key::Key::F19,
        KeyCode::F20 => key::Key::F20,
        KeyCode::F21 => key::Key::F21,
        KeyCode::F22 => key::Key::F22,
        KeyCode::F23 => key::Key::F23,
        KeyCode::F24 => key::Key::F24,
        KeyCode::F25 => key::Key::F25,
        KeyCode::MediaPlayPause => key::Key::MediaPlayPause,
        KeyCode::MediaStop => key::Key::MediaStop,
        KeyCode::MediaTrackNext => key::Key::MediaTrackNext,
        KeyCode::MediaTrackPrevious => key::Key::MediaTrackPrevious,
        KeyCode::MediaSelect => key::Key::MediaSelect,
        KeyCode::AudioVolumeDown => key::Key::AudioVolumeDown,
        KeyCode::AudioVolumeMute => key::Key::AudioVolumeMute,
        KeyCode::AudioVolumeUp => key::Key::AudioVolumeUp,
        KeyCode::Eject => key::Key::Eject,
        KeyCode::Power => key::Key::Power,
        KeyCode::Sleep => key::Key::Sleep,
        KeyCode::WakeUp => key::Key::WakeUp,
        KeyCode::Copy => key::Key::Copy,
        KeyCode::Cut => key::Key::Cut,
        KeyCode::Paste => key::Key::Paste,
        KeyCode::BrowserBack => key::Key::BrowserBack,
        KeyCode::BrowserForward => key::Key::BrowserForward,
        KeyCode::BrowserHome => key::Key::BrowserHome,
        KeyCode::BrowserRefresh => key::Key::BrowserRefresh,
        KeyCode::BrowserSearch => key::Key::BrowserSearch,
        KeyCode::BrowserStop => key::Key::BrowserStop,
        KeyCode::BrowserFavorites => key::Key::BrowserFavorites,
        KeyCode::LaunchApp1 => key::Key::LaunchApp1,
        KeyCode::LaunchApp2 => key::Key::LaunchApp2,
        KeyCode::LaunchMail => key::Key::LaunchMail,
        _ => return None,
    })
}

pub fn map_mods(mods: &winit::event::Modifiers) -> key::Mods {
    let state = mods.state();
    let mut m = key::Mods::empty();
    if state.shift_key() {
        m |= key::Mods::SHIFT;
    }
    if state.control_key() {
        m |= key::Mods::CTRL;
    }
    if state.alt_key() {
        m |= key::Mods::ALT;
        // Required for the libghostty-vt encoder's `macos_option_as_alt =
        // left/right` branch. `ALT_SIDE` unset means left. Gate on the right
        // side only — `lalt_state` may report `Unknown` on some platforms
        // while `ralt_state` reports `Pressed`.
        if matches!(
            mods.ralt_state(),
            winit::keyboard::ModifiersKeyState::Pressed
        ) {
            m |= key::Mods::ALT_SIDE;
        }
    }
    if state.super_key() {
        m |= key::Mods::SUPER;
    }
    m
}

pub fn map_action(state: winit::event::ElementState) -> key::Action {
    match state {
        winit::event::ElementState::Pressed => key::Action::Press,
        winit::event::ElementState::Released => key::Action::Release,
    }
}
